Add basic documentation
serokell/config_macro pull request #1
Opened 2019-02-05 16:23 UTC by mkaito

It's mostly boiler plate with a link to HexDocs, but it's better than nothing.

2019-02-17 16:37 UTC, gromakovsky requested changes
There are some leftovers from the template.

2019-02-17 16:37 UTC, gromakovsky commented on README.md
> +[![Release](https://img.shields.io/github/release/serokell/patak.svg)](https://github.com/serokell/patak/releases)
Should be removed.

2019-02-17 16:37 UTC, gromakovsky commented on README.md
> +## For Contributors [↑](#-patak)
Please remove these `(#-patak)` or turn them into working links.

2019-02-18 12:45 UTC, mkaito commented
Thanks, I missed those. Should be fixed now.

2019-02-18 13:06 UTC, gromakovsky approved these changes

2019-02-18 16:25 UTC, merged